🗄️ PHASE 2: SQL Analysis

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import MaxNLocator

# Load all datasets 
DATA_PATH = '/Users/tizianogallo/Desktop/Github/f1-analysis/data/'

races        = pd.read_csv(DATA_PATH + 'races.csv')
results      = pd.read_csv(DATA_PATH + 'results.csv')
drivers      = pd.read_csv(DATA_PATH + 'drivers.csv')
constructors = pd.read_csv(DATA_PATH + 'constructors.csv')
lap_times    = pd.read_csv(DATA_PATH + 'lap_times.csv')
pit_stops    = pd.read_csv(DATA_PATH + 'pit_stops.csv')
qualifying   = pd.read_csv(DATA_PATH + 'qualifying.csv')
standings    = pd.read_csv(DATA_PATH + 'driver_standings.csv')
circuits     = pd.read_csv(DATA_PATH + 'circuits.csv')

# Quick sanity check
for name, df in zip(['races','results','drivers','constructors'], 
                    [races, results, drivers, constructors]):
    print(f"{name}: {df.shape} | NaN%: {df.isnull().mean().mean():.2%}")

races: (1125, 18) | NaN%: 0.00%
results: (26759, 18) | NaN%: 0.00%
drivers: (861, 9) | NaN%: 0.00%
constructors: (212, 5) | NaN%: 0.00%

In [4]:
# Replace '\\N' (Ergast null marker) with NaN
for df in [results, qualifying, lap_times, pit_stops]:
    df.replace('\\N', np.nan, inplace=True)

# Parse numeric columns
results['position']      = pd.to_numeric(results['positionOrder'], errors='coerce')
results['grid']          = pd.to_numeric(results['grid'], errors='coerce')
results['points']        = pd.to_numeric(results['points'], errors='coerce')
results['milliseconds']  = pd.to_numeric(results['milliseconds'], errors='coerce')
lap_times['milliseconds']= pd.to_numeric(lap_times['milliseconds'], errors='coerce')

# Parse qualifying times to milliseconds
def time_to_ms(t):
    try:
        m, s = str(t).split(':')
        return int(m) * 60000 + float(s) * 1000
    except:
        return np.nan

for col in ['q1', 'q2', 'q3']:
    qualifying[f'{col}_ms'] = qualifying[col].apply(time_to_ms)

# Add driver full name
drivers['full_name'] = drivers['forename'] + ' ' + drivers['surname']

# Merge year into results
results = results.merge(races[['raceId', 'year', 'circuitId']], on='raceId')

2.1 Set Up SQLite

In [5]:
import sqlite3

conn = sqlite3.connect('/Users/tizianogallo/Desktop/Github/f1-analysis/f1_analysis.db')

# Load all CSVs into SQLite
tables = {
    'races': races, 'results': results, 'drivers': drivers,
    'constructors': constructors, 'lap_times': lap_times,
    'pit_stops': pit_stops, 'qualifying': qualifying,
    'driver_standings': standings, 'circuits': circuits
}
for table_name, df in tables.items():
    df.to_sql(table_name, conn, if_exists='replace', index=False)

print("Database loaded successfully.")

Database loaded successfully.

2.2 Core SQL Queries

In [11]:
def run_query(sql, conn=conn):
    return pd.read_sql_query(sql, conn)

In [18]:
# 1. All-time driver wins leaderboard
df_wins = run_query("""
    SELECT 
        d.forename || ' ' || d.surname AS driver,
        d.nationality,
        COUNT(*) AS wins
    FROM results r
        JOIN drivers d ON r.driverId = d.driverId
    WHERE r.positionOrder = 1
    GROUP BY d.driverId
    ORDER BY wins DESC
    LIMIT 15;
""")
df_wins

                driver nationality  wins
0       Lewis Hamilton     British   105
1   Michael Schumacher      German    91
2       Max Verstappen       Dutch    63
3     Sebastian Vettel      German    53
4          Alain Prost      French    51
5         Ayrton Senna   Brazilian    41
6      Fernando Alonso     Spanish    32
7        Nigel Mansell     British    31
8       Jackie Stewart     British    27
9            Jim Clark     British    25
10          Niki Lauda    Austrian    25
11         Juan Fangio   Argentine    24
12       Nelson Piquet   Brazilian    23
13        Nico Rosberg      German    23
14          Damon Hill     British    22

In [19]:
# 2. Average pit stop duration by team (modern era 2011+)

df_wins = run_query("""
    SELECT 
        c.name AS constructor,
        ROUND(AVG(p.milliseconds) / 1000.0, 2) AS avg_pit_seconds,
        COUNT(*) AS total_stops
    FROM pit_stops p
        JOIN results r ON p.raceId = r.raceId AND p.driverId = r.driverId
        JOIN constructors c ON r.constructorId = c.constructorId
        JOIN races ra ON p.raceId = ra.raceId
    WHERE ra.year >= 2011 AND p.milliseconds IS NOT NULL
    GROUP BY c.constructorId
    HAVING total_stops > 100
    ORDER BY avg_pit_seconds ASC;
""")
df_wins

       constructor  avg_pit_seconds  total_stops
0         Lotus F1            32.46          285
1              HRT            32.68          150
2         Caterham            33.92          241
3         Marussia            34.40          233
4       Toro Rosso            44.49          683
5      Force India            50.85          609
6           Sauber            57.25          708
7          Renault            63.26          403
8         Williams            76.77         1110
9   Manor Marussia            84.03          156
10         Ferrari            84.86         1081
11        Red Bull            84.99         1127
12        Mercedes            89.25         1110
13         McLaren            93.41         1092
14    Haas F1 Team           103.07          676
15    Racing Point           104.67          118
16      Alfa Romeo           148.32          380
17    Aston Martin           172.89          338
18  Alpine F1 Team           176.03          309
19      AlphaTauri           181.16          322

In [20]:
# 3. Grid-to-win conversion rate by driver (min 50 pole positions)
df_wins = run_query("""
    SELECT
        d.forename || ' ' || d.surname AS driver,
        SUM(CASE WHEN r.grid = 1 THEN 1 ELSE 0 END) AS poles,
        SUM(CASE WHEN r.grid = 1 AND r.positionOrder = 1 THEN 1 ELSE 0 END) AS pole_to_wins,
        ROUND(100.0 * SUM(CASE WHEN r.grid = 1 AND r.positionOrder = 1 THEN 1 ELSE 0 END)
            / NULLIF(SUM(CASE WHEN r.grid = 1 THEN 1 ELSE 0 END), 0), 1) AS conversion_pct
    FROM results r
        JOIN drivers d ON r.driverId = d.driverId
    GROUP BY d.driverId
    HAVING poles >= 10
    ORDER BY conversion_pct DESC;
""")
df_wins

                driver  poles  pole_to_wins  conversion_pct
0       Max Verstappen     40            32            80.0
1       Alberto Ascari     14             9            64.3
2      Fernando Alonso     22            14            63.6
3   Michael Schumacher     68            40            58.8
4       Lewis Hamilton    104            61            58.7
5          Alain Prost     33            18            54.5
6     Sebastian Vettel     57            31            54.4
7        Nigel Mansell     32            17            53.1
8           James Hunt     14             7            50.0
9         Felipe Massa     16             8            50.0
10        Nico Rosberg     30            15            50.0
11      Jackie Stewart     17             8            47.1
12        Jack Brabham     13             6            46.2
13         Juan Fangio     29            13            44.8
14        Ayrton Senna     65            29            44.6
15      Mario Andretti     18             8            44.4
16           Jim Clark     34            15            44.1
17      Gerhard Berger     12             5            41.7
18       Stirling Moss     17             7            41.2
19       Mika Häkkinen     26            10            38.5
20  Jacques Villeneuve     13             5            38.5
21          Niki Lauda     24             9            37.5
22  Rubens Barrichello     14             5            35.7
23          Damon Hill     20             7            35.0
24      Kimi Räikkönen     18             6            33.3
25         Graham Hill     13             4            30.8
26          Jacky Ickx     13             4            30.8
27         Mark Webber     13             4            30.8
28     Valtteri Bottas     20             6            30.0
29        Jochen Rindt     10             3            30.0
30  Juan Pablo Montoya     13             3            23.1
31     Ronnie Peterson     14             3            21.4
32       Nelson Piquet     24             5            20.8
33     Charles Leclerc     26             5            19.2
34     David Coulthard     12             2            16.7
35         René Arnoux     18             2            11.1

In [ ]:
# 4. Constructors' championship dominance (win % per season)
df_wins = run_query("""
SELECT
    ra.year,
    c.name AS constructor,
    COUNT(*) AS races,
    SUM(CASE WHEN r.positionOrder = 1 THEN 1 ELSE 0 END) AS wins,
    ROUND(100.0 * SUM(CASE WHEN r.positionOrder = 1 THEN 1 ELSE 0 END) / COUNT(*), 1) AS win_pct
FROM results r
JOIN races ra ON r.raceId = ra.raceId
JOIN constructors c ON r.constructorId = c.constructorId
WHERE r.grid > 0
GROUP BY ra.year, c.constructorId
HAVING wins > 0
ORDER BY ra.year DESC, wins DESC;
""")
df_wins

     year   constructor  races  wins  win_pct
0    2024      Red Bull     47     9     19.1
1    2024       McLaren     48     6     12.5
2    2024       Ferrari     47     5     10.6
3    2024      Mercedes     47     4      8.5
4    2023      Red Bull     42    21     50.0
..    ...           ...    ...   ...      ...
272  1951    Alfa Romeo     30     5     16.7
273  1951       Ferrari     33     3      9.1
274  1951  Kurtis Kraft     17     1      5.9
275  1950    Alfa Romeo     22     6     27.3
276  1950  Kurtis Kraft     15     1      6.7

[277 rows x 5 columns]

In [22]:
# 5. DNF (Did Not Finish) rate by driver (modern era)
df_wins = run_query("""
    SELECT
        d.forename || ' ' || d.surname AS driver,
        COUNT(*) AS total_starts,
        SUM(CASE WHEN r.positionOrder > r.laps THEN 1 ELSE 0 END) AS dnfs,
        ROUND(100.0 * SUM(CASE WHEN r.positionOrder > r.laps THEN 1 ELSE 0 END) / COUNT(*), 1) AS dnf_pct
    FROM results r
        JOIN drivers d ON r.driverId = d.driverId
        JOIN races ra ON r.raceId = ra.raceId
    WHERE ra.year >= 2010
    GROUP BY d.driverId
    HAVING total_starts >= 30
    ORDER BY dnf_pct ASC;
""")
df_wins

                driver  total_starts  dnfs  dnf_pct
0         Lando Norris           128     4      3.1
1        Paul di Resta            59     2      3.4
2         Felipe Massa           155     6      3.9
3      Valtteri Bottas           247    11      4.5
4       Lewis Hamilton           304    14      4.6
5     Daniel Ricciardo           257    12      4.7
6       George Russell           128     6      4.7
7        Robert Kubica            42     2      4.8
8    Heikki Kovalainen            60     3      5.0
9          Felipe Nasr            40     2      5.0
10    Sebastian Vettel           257    13      5.1
11         Charles Pic            39     2      5.1
12  Rubens Barrichello            38     2      5.3
13      Logan Sargeant            36     2      5.6
14      Kimi Räikkönen           195    12      6.2
15     Fernando Alonso           264    17      6.4
16         Mark Webber            77     5      6.5
17       Oscar Piastri            46     3      6.5
18        Nico Rosberg           136     9      6.6
19        Sergio Pérez           283    19      6.7
20   Stoffel Vandoorne            42     3      7.1
21        Lance Stroll           168    12      7.1
22       Jenson Button           137    10      7.3
23         Guanyu Zhou            68     5      7.4
24     Alexander Albon           105     8      7.6
25   Jaime Alguersuari            38     3      7.9
26     Kevin Magnussen           186    15      8.1
27      Max Verstappen           209    17      8.1
28  Antonio Giovinazzi            62     5      8.1
29     Charles Leclerc           149    12      8.1
30     Nicholas Latifi            61     5      8.2
31        Esteban Ocon           156    13      8.3
32         Max Chilton            35     3      8.6
33        Carlos Sainz           208    18      8.7
34       Jules Bianchi            34     3      8.8
35        Pierre Gasly           154    15      9.7
36   Esteban Gutiérrez            59     6     10.2
37  Michael Schumacher            58     6     10.3
38    Jean-Éric Vergne            58     6     10.3
39     Marcus Ericsson            97    10     10.3
40        Daniil Kvyat           112    12     10.7
41        Jarno Trulli            37     4     10.8
42     Nico Hülkenberg           230    26     11.3
43     Mick Schumacher            44     5     11.4
44        Adrian Sutil            76     9     11.8
45       Vitaly Petrov            58     7     12.1
46        Yuki Tsunoda            90    11     12.2
47     Pascal Wehrlein            39     5     12.8
48          Timo Glock            58     8     13.8
49     Romain Grosjean           174    25     14.4
50     Kamui Kobayashi            74    11     14.9
51    Pastor Maldonado            96    15     15.6
52     Sébastien Buemi            38     6     15.8
53         Bruno Senna            46     8     17.4
54   Vitantonio Liuzzi            37     7     18.9
55    Pedro de la Rosa            35     7     20.0
56       Jolyon Palmer            37     8     21.6

2.3 Running SQL in Python

In [23]:
def run_query(sql, conn=conn):
    return pd.read_sql_query(sql, conn)

df_wins = run_query("""
    SELECT d.forename || ' ' || d.surname AS driver, COUNT(*) AS wins
    FROM results r JOIN drivers d ON r.driverId = d.driverId
    WHERE r.positionOrder = 1 GROUP BY d.driverId ORDER BY wins DESC LIMIT 15
""")
print(df_wins)

                driver  wins
0       Lewis Hamilton   105
1   Michael Schumacher    91
2       Max Verstappen    63
3     Sebastian Vettel    53
4          Alain Prost    51
5         Ayrton Senna    41
6      Fernando Alonso    32
7        Nigel Mansell    31
8       Jackie Stewart    27
9            Jim Clark    25
10          Niki Lauda    25
11         Juan Fangio    24
12       Nelson Piquet    23
13        Nico Rosberg    23
14          Damon Hill    22